# command shortcuts
alias sizes="find . -type f -exec du -h {} + | sort -r -h | head"
alias ls="ls -alh"
alias pu="pip install --upgrade pip"
alias pf="pip freeze > requirements.txt"
alias add="git add"
alias commit="git commit -m"
alias ac="git add -A && git commit -m"
alias push="git push"
alias pull="git pull"
alias status="git status"
alias s="git status"
alias diff="git diff"
alias clone="git clone"
alias checkout="git checkout"
alias stash="git stash"
alias c="code"
alias p="poetry"
alias u="pytest"
alias d="docker"
alias dc="docker container"
alias di="docker image"
alias rui="autoflake --remove-all-unused-imports --in-place -r ."
alias t="terraform"



# directory shortcuts
alias dt="cd ~/Desktop/"
alias dl="cd ~/Downloads/"
alias gd="cd ~/Google\ Drive/My\ Drive/"
alias ry="cd ~/repository/"