#!/bin/bash
path=$1
removestar -i $path
find $path -name "*.py" -exec pyupgrade --py311-plus {} \;
black $path
isort $path
autoflake --remove-all-unused-imports --in-place -r $path
docformatter -r --in-place $path




