#!/bin/bash
path=$1
removestar -i $path
find $path -name "*.py" -exec pyupgrade --py311-plus {} \;
black $path
autoflake --remove-all-unused-imports --remove-unused-variables --in-place -r .
isort $path
find $path -name '*.py' -exec docformatter --wrap-summaries 88 --wrap-descriptions 88 --in-place {} \;
find $path -name '*.json' -exec python -m json.tool --indent 4 {} {} \;
find $path \( -name "*.yml" -o -name "*.yaml" \) -exec yq --prettyPrint --indent 2 -i {} \;
# find $path -name '*.sql' -exec sqlformat {} --reindent --keywords upper --use_space_around_operators -o {} \;
# use sqlfluff instead of sqlformat