#!/bin/bash

MESSAGE=$1

# List of files to process
REPOS=(clmac nuttk bashtk sandbox dstk)

# Loop through files and run command on each
for repo in "${REPOS[@]}"; do
  cd "$repo" || exit
  giter . "$MESSAGE"
  cd ..
done
