alias venv="if [ -e ./.venv/bin/activate ]; then source ./.venv/bin/activate; else python3 -m venv .venv && source ./.venv/bin/activate; fi"
alias sizes="find . -type f -exec du -h {} + | sort -r -h | head"
alias pc="pycharm"
alias ls="ls -alh"
alias pu="pip install --upgrade pip"
alias pf="pip freeze > requirements.txt"